In [1]:
import numpy as np

In [3]:
small_counts = np.random.randint(0,100,20)
small_counts

array([40,  8, 72, 59, 94, 31, 50, 41, 74, 23, 77, 54, 80, 61, 10, 11,  3,
       91, 93, 27])

In [4]:
np.floor_divide(small_counts,10)

array([4, 0, 7, 5, 9, 3, 5, 4, 7, 2, 7, 5, 8, 6, 1, 1, 0, 9, 9, 2])

In [7]:
large_counts = [300,296, 8286, 64011, 80, 3, 725, 867, 2215, 7689, 11495, 91897,44, 28, 7971, 926, 122, 22222]

In [9]:
(np.log10(large_counts))

array([2.47712125, 2.47129171, 3.91834493, 4.80625461, 1.90308999,
       0.47712125, 2.86033801, 2.9380191 , 3.34537373, 3.88586986,
       4.06050898, 4.96330133, 1.64345268, 1.44715803, 3.90151281,
       2.96661099, 2.08635983, 4.34678314])